### ISSUE TITLE
Órden en el diseño de la base de datos

### ISSUE THREAD

**Issue by dhabyx** [ahuitz/FinalPortalURL#4]
Es necesario que en el diseño de la base de datos se agrupen las tablas por módulos, ya que así es mas fácil entender cómo funcionan.

Es recomendable el uso de "Layers" para agrupar las tablas.

![workbenchlayers](https://cloud.githubusercontent.com/assets/290991/8513474/a2085220-2329-11e5-8f47-cecd0bbae273.png)

**Comment by yesicanoemi** [comment]
Esta bien ingeniero, todos estamos de acuerdo para que se pase el proyecto
a esa fecha. Una pregunta para que fecha esta el Examen Final

**Comment by dhabyx** [comment]
Saludos Yesica

Aún no han pasado el calendario de exámenes de coordinación.

On 05/07/15 15:27, yesicanoemi wrote:

> Esta bien ingeniero, todos estamos de acuerdo para que se pase el proyecto
> a esa fecha. Una pregunta para que fecha esta el Examen Final
> 
> El 5 de julio de 2015, 15:22, DhabyX notifications@github.com escribió:
> 
> > Es necesario que en el diseño de la base de datos se agrupen las tablas
> > por módulos, ya que así es mas fácil entender cómo funcionan.
> > 
> > Es recomendable el uso de "Layers" para agrupar las tablas.
> > 
> > [image: workbenchlayers]
> > 
> > https://cloud.githubusercontent.com/assets/290991/8513474/a2085220-2329-11e5-8f47-cecd0bbae273.png
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/ahuitz/FinalPortalURL/issues/4.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ahuitz/FinalPortalURL/issues/4#issuecomment-118668603.

## 

Dhaby Xiloj
