### ISSUE TITLE
Nombres de tablas en las bases de datos

### ISSUE THREAD

**Issue by dhabyx** [ahuitz/FinalPortalURL#5]
Es recomendable cambiar el nombre de las tablas a un estándar mucho mas efectivo, ésto ayudará a mejorar la forma de utilizarlo en la codificación, ya que cada tabla en el mapeo a objetos, en JPA, se convierte en una entidad.

Un enlace interesante para aprender a nombrar las tablas es el siguiente: [SQL Server Standards](http://www.isbe.net/ILDS/pdf/SQL_server_standards.pdf)

**Comment by ahuitz** [comment]
se ha cambiado la BD con los cambios sugeridos
