### ISSUE TITLE
Asociación entre cursos y carrera

### ISSUE THREAD

**Issue by dhabyx** [ahuitz/FinalPortalURL#7]
No existe una forma de saber qué cursos pertenecen a cada carrera.

**Comment by ahuitz** [comment]
se han realizado todos los cambios indicados, si fuera tan amable de indicarnos si estamos en lo correcto, gracias!

**Comment by dhabyx** [comment]
Aún no es posible vincular cursos con carrera, qué pasaría cuando queremos asignarle un curso a un estudiante, pero tenermos varios cursos con el mismo nombre en varias carreras?

**Comment by ahuitz** [comment]
se ha modificado la BD, esperamos nuevas correcciones
